# Generated by Django 5.1.6 on 2025-03-02 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='programme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.programme'),
        ),
    ]
