# Generated by Django 5.1.6 on 2025-03-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_coursematerial_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/course_images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profiles/profile.png', null=True, upload_to='images/student_profiles/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profiles/profile.png', null=True, upload_to='images/profiles/'),
        ),
    ]
