# Generated by Django 5.1.6 on 2025-03-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profiles/profile.jpg', null=True, upload_to='images/profiles/'),
        ),
    ]
