# Generated by Django 5.1.6 on 2025-03-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='images/course_images/default.jpg', null=True, upload_to='images/course_images/'),
        ),
    ]
