# Generated by Django 5.1.6 on 2025-03-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='programme',
        ),
        migrations.AddField(
            model_name='course',
            name='programmes',
            field=models.ManyToManyField(blank=True, related_name='courses', to='students.programme'),
        ),
    ]
