# Generated by Django 5.1.6 on 2025-04-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_course_programme_course_programmes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='intake_date',
        ),
    ]
