# Generated by Django 5.1.6 on 2025-04-08 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_student_intake_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='intake_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
    ]
