# Generated by Django 5.1.6 on 2025-03-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
        ('students', '0003_course_image_student_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='programme',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='programme',
            field=models.ManyToManyField(to='students.programme'),
        ),
    ]
